CREATE TABLE BRAND
(
    BRAND_ID   BIGINT PRIMARY KEY,
    BRAND_NAME VARCHAR(50),
    FOUND_DATE DATE
);

CREATE DOMAIN CAR_BODY_TYPE AS TEXT
    CHECK (
                VALUE = 'HATCHBACK'
            OR VALUE = 'SEDAN'
            OR VALUE = 'COUPE'
            OR VALUE = 'PICKUP TRUCK'
            OR VALUE = 'ROADSTER'
            OR VALUE = 'STATION WAGON'
        );

CREATE TABLE MODEL
(
    MODEL_ID   BIGINT PRIMARY KEY,
    MODEL_NAME VARCHAR(50),
    LENGTH     INT,
    WIDTH      INT,
    TYPE       CAR_BODY_TYPE,
    BRAND      BIGINT,
    CONSTRAINT FK_BRAND
        FOREIGN KEY (BRAND)
            REFERENCES BRAND (BRAND_ID) ON DELETE CASCADE
);

