create table users
(
    USER_ID  BIGINT PRIMARY KEY,
    LOGIN    VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE     VARCHAR(255),
    BRAND BIGINT NOT NULL,
    CONSTRAINT FK_BRAND
        FOREIGN KEY (BRAND)
            REFERENCES BRAND (BRAND_ID) ON DELETE CASCADE
)